[project]
name = "lexrank"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Viliam Schrojf", email = "viliam@schrojf.sk" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
]

[project.scripts]
lexrank = "lexrank.cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
